
package edu.vistas;

import edu.dao.DaoUsuario;
import edu.modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import ds.desktop.notify.DesktopNotify;
import ds.desktop.notify.NotifyTheme;
import edu.dao.DaoNotificacion;
import edu.modelo.Notificacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 * Nombre de la clase: Menu
 * Version: 1.9
 * Fecha:11/08/18
 * CopyRight:SSE-ITCA
 * @author Roxana Menjivar
 */
public class Menu extends javax.swing.JFrame {

    FrmCoordinador gestionC;
    Notificaciones frmNoti;
    FrmHorario gestionH;
    FrmSolicitudes gestionS;
    FrmUsuario gestionU;
    Usuario use=new Usuario();
     public static List lsUs;
    public static boolean FormularioVal=false;
    DaoNotificacion noti=new DaoNotificacion();

    private Timer timer;
    private int delay = 30000;
    
    public Menu() {
        initComponents(); 
        this.setExtendedState(MAXIMIZED_BOTH);        
    }  
    
    public void correr()
    {        
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                ActionListener action = new ActionListener()
                {   
                    @Override
                    public void actionPerformed(ActionEvent ae) 
                    {
                        timer.stop();                     
                        int numero=noti.getNoti();
                        if (numero>0) 
                        {
                            DesktopNotify.showDesktopMessage("", "Tienes "+numero+" de Solicitudes de SSE\n ¿desea atenderlas ahora?",DesktopNotify.INPUT_REQUEST, new ActionListener() 
                            {
                                @Override
                                public void actionPerformed(ActionEvent ae) 
                                {

                                    int SioNo = JOptionPane.showConfirmDialog(null, "¿Desea revisar solicuudes?", "Advertencia", JOptionPane.YES_NO_OPTION);                            
                                    if (SioNo == 0) 
                                    {
                                        abrirNotificaciones(); 
                                        timer.start();
                                    }
                                    else
                                    {
                                        timer.start();
                                    }
                                }                            
                            });

                        }
                            
                    }
                };
                timer = new Timer(delay, action);
                timer.setInitialDelay(0);
                timer.start();
            }
        });
    }
    
    public void abrirNotificaciones()
    {
         if(FormularioVal==false)
        {
            this.frmNoti = new Notificaciones();
            this.desktopPane.add(frmNoti);
            frmNoti.setVisible(true);
            frmNoti.setLocation(
            desktopPane.getWidth()/2 - frmNoti.getWidth()/2,
            desktopPane.getHeight()/2 - frmNoti.getHeight()/2);
            FormularioVal=true;
        }
    }
    
    public void pasarDatos(List r)
    {
        lsUs=r; 
        try {
            this.setTitle("Sistema SSE - "+lsUs.get(0).toString());
        } catch (Exception e) {
            
        }
        
    }

    public static List getLsUs() 
    {
        return lsUs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        GestionarUsuario = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        GestionCoordinador = new javax.swing.JMenu();
        GestionHorarios = new javax.swing.JMenu();
        editMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(java.awt.SystemColor.activeCaption);

        GestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/us.png"))); // NOI18N
        GestionarUsuario.setText("Gestion de Usuarios");
        GestionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionarUsuarioMouseClicked(evt);
            }
        });
        menuBar.add(GestionarUsuario);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/sss.png"))); // NOI18N
        jMenu2.setText("Solicitudes");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        GestionCoordinador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/coordinador.png"))); // NOI18N
        GestionCoordinador.setMnemonic('f');
        GestionCoordinador.setText("Gestion de Coordinador");
        GestionCoordinador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionCoordinadorMouseClicked(evt);
            }
        });
        menuBar.add(GestionCoordinador);

        GestionHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/calendar.png"))); // NOI18N
        GestionHorarios.setMnemonic('e');
        GestionHorarios.setText("Gestion de Horarios");
        GestionHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionHorariosMouseClicked(evt);
            }
        });
        menuBar.add(GestionHorarios);

        editMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/iconos/reporte.png"))); // NOI18N
        editMenu1.setMnemonic('e');
        editMenu1.setText("Reportes");
        menuBar.add(editMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionCoordinadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionCoordinadorMouseClicked
        if(FormularioVal==false)
        {
            this.gestionC = new FrmCoordinador();
            this.desktopPane.add(gestionC);
            gestionC.setVisible(true);
            gestionC.setLocation(
            desktopPane.getWidth()/2 - gestionC.getWidth()/2,
            desktopPane.getHeight()/2 - gestionC.getHeight()/2);
            FormularioVal=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ya tiene una ventana abierta!");
        }
    }//GEN-LAST:event_GestionCoordinadorMouseClicked
   
    public void cerrar()
    {
         FormularioVal=false;
    }
    
    private void GestionHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionHorariosMouseClicked
        if(FormularioVal==false)
        {
            this.gestionH = new FrmHorario();
            this.desktopPane.add(gestionH);
            gestionH.setVisible(true);
            gestionH.setLocation(
                    desktopPane.getWidth()/2 - gestionH.getWidth()/2,
                    desktopPane.getHeight()/2 - gestionH.getHeight()/2);
                    FormularioVal=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ya tiene una ventana abierta!");
        }
    }//GEN-LAST:event_GestionHorariosMouseClicked

    
    public void mostraSolis()
    {
            if(FormularioVal==false)
        {
            this.gestionS = new FrmSolicitudes();
            this.desktopPane.add(gestionS);
            gestionS.setVisible(true);
            gestionS.setLocation(
                    desktopPane.getWidth()/2 - gestionS.getWidth()/2,
                    desktopPane.getHeight()/2 - gestionS.getHeight()/2);
                    FormularioVal=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ya tiene una ventana abierta!");
        }
    }
    
    
    public void frmSoli(int x)
    {
        FrmSolicitud frms = new FrmSolicitud(x);
        this.desktopPane.add(frms);
        frms.setVisible(true);
    }
    private void GestionarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarUsuarioMouseClicked
        if(FormularioVal==false)
        {
            this.gestionU = new FrmUsuario();
            this.desktopPane.add(gestionU);
            gestionU.setVisible(true);
            gestionU.setLocation(
            desktopPane.getWidth()/2 - gestionU.getWidth()/2,
            desktopPane.getHeight()/2 - gestionU.getHeight()/2);
            FormularioVal=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ya tiene una ventana abierta!");
        }
    }//GEN-LAST:event_GestionarUsuarioMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        mostraSolis();
    }//GEN-LAST:event_jMenu2MouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GestionCoordinador;
    private javax.swing.JMenu GestionHorarios;
    private javax.swing.JMenu GestionarUsuario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
